- ec2system/ec2machine.go
Private dns names are not always resolvable outside of AWS, this PR avoids using them and instead uses their IP address directly. Public dns and ip address are still preferred over the private ip.
> ec2machine: do not attempt to use a private dns address

- cmd/ec2boot/install.bash
- ec2system/ec2machine.go
- go.mod
- go.sum
- machine.go
- machine_test.go
- supervisor.go
This change separates binary upload from binary exec, so that a separate
timeout may be specified in teh case of the former. This allows
Bigmachine-systems to run in more bandwidth constrained scenarios.
This timeout is now computed based on a bandwidth floor of 100 kB/s.
(Arbitrary but reasonable.)
The change also adds a Getbinary method to the supervisor so that we can
distribute binaries among workers instead of re-uploading the binary
every time. (Implementing this is a future change.)
While this change improves the chances of success in bandwidth
constrained setups, using an overall timeout for stall detection is
still suboptimal. Future work includes monitoring upload progress
directly, and failing on stalls.
> separate binary upload from exec

- ec2system/config.go
- ec2system/ec2machine.go
Instead of hardcoding ec2boot in the config (which materializes to, e.g., $HOME/.bigslice/config), we set the default to an empty string, and fill in the default binary associated with the current release.
We also rewrite binaries with the  official prefix to match the current version.
> ec2system: change handling of default ec2boot binaries

- cmd/ec2boot/install.bash
- ec2system/config.go
- ec2system/ec2machine.go
- ec2system/ec2machine_test.go
As outlined in #15, ec2system can currently recycle machine
addresses. This could be bad for downstream systems that depend on
addresses being unique (e.g., Bigslice storing the location of tasks
this way).
This fixes the problem by using the instance id as the URL prefix.
This has several advantages: first, it can be computed independently
in the driver and the worker; second, the URL carries meaningful
information: e.g., the EC2 instance ID is unique and can be used to
look up entries in cloudwatch, etc.
> ec2system: add URL prefix to prevent address recycling

- machine.go
Restore machine-prefixing of logs which was inadvertently removed in 1e5f7ff.
> Restore machine-prefixing of logs

- bigmachine.go
- machine_test.go
Simplify waiting for log propagation by:
- using a `sync.WaitGroup` instead of an `errgroup.Group`.  We don't use any of the error propagation or context cancellation features of `errgroup.Group`.
- using an unbuffered channel for `tailDone`.  We only communicate by closing the channel, so buffering is immaterial.  When reading code, no one has to wonder, "why is this buffered?", like I did.
I arrived here because internal linting complained about not checking the error return of `grp.Wait()`, and I decided to simplify rather than explicitly ignoring the error and adding a comment explaining why.
> Simplify waiting for log propagation

- ec2system/config.go
- ec2system/ec2machine.go
- go.mod
- go.sum
- local.go
- machine.go
- system.go
- testsystem/testsystem.go
Add logging of semi-structured events. These events can be used for (ad hoc) analytics, e.g. count how many machines were lost, compare number of spot instances, etc. Some of this information could be derived from a cloud provider, however this mechanism has some nice properties: it provides the perspective of bigmachine (e.g. a machine could still be running in EC2, but not available to bigmachine); it makes it easy to unify with other events (e.g. we can log keepalive RPC call behavior and compare it to RPC call behavior from other layers); it's lightweight to add new events.
For this initial addition, we log a few events (with immediate utility to GRAIL):
* `bigmachine:machineError`: we have an error reaching a machine and consider it stopped.
* `bigmachine:machineStop`: a machine is …
> Add eventlog logging

- internal/filebuf/filebuf.go
- internal/filebuf/filebuf_test.go
- profile.go
Use temporary files to buffer profiles that we aggregate from other machines. The existing code buffers in memory, and some computations produce large profiles, e.g. large goroutine profiles. Instead, download the profiles into temporary files before merging them.
> Use temporary files to buffer profiles

- ec2system/config.go
Make the default Eventer nil, as this is probably the least surprising behavior.
> Make default Eventer nil

- rpc/client.go
Close all connections when "resetting" clients. We reset clients by disposing of the clients and backing transports on error. Transports are only garbage collected when all connections, including idle connections, are closed. The existing code was not handling the case in which successful requests followed failed requests. We would eject the client from our cache, but subsequent successful requests would not close the remaining transport connections. The end result is that client resets could cause transport leaks. This is problematic for very long-running computations.
Change this to close idle connections on clients/transports that have been reset.
> Close all connections when resetting clients

- ec2system/ec2machine.go
Add context strings to spot instance request errors to make it easier to interpret the error messages.
> Add context to spot instance request errors

- .travis.yml
Travis tells me that this field has no effect.
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Remove `sudo` field

- ec2system/ec2machine.go
Prevent reboot of EC2 instances. There are a few scenarios in which the instance may try to reboot:
- EC2 rebooting when encountering underlying hardware issues.
- EC2 scheduled maintenance.
- Services running that cause reboot, e.g. locksmithd. (This one is avoidable by using an appropriate AMI).
We prevent rebooting because bringing the instance back to a working state would add a lot of complexity, as we would need restore both internal state and the state of defined services.
> Prevent reboot of EC2 instances

- ec2system/ec2machine.go
Make indentation of cloud unit and file contents consistent, mostly to avoid future wonder about why they might be different. The differences are eliminated anyway by the `tmpl` function.
> Make indentation of cloud {units,files} consistent

- local.go
Bookkeep the muxer used to merge `Stdout` and `Stderr` from the machine process, which is used to tail logs from the machine. We construct a map keyed by machine pointer key, but we use a `nil` key. Fix to use the correct machine pointer.
`Tail` now works correctly, instead of showing the message, "machine not under management".
> Bookkeep muxer correctly for local system Tail

- rpc/client.go
`Call` and `RetryCall` can take an `io.Reader` as an argument. There is a subtle (to me) implication in the `RetryCall` case. If the call needs retrying, subsequent calls will just get whatever state of the `io.Reader` is left over from previous attempts. This can be problematic for some (many?) use cases.
Introduce the ability to pass a `func() io.Reader` which will be called for each `Call` to produce the reader for the argument.
This will be used to make [a recently added usage of an `io.Reader` argument in Bigslice](https://github.com/grailbio/bigslice/blob/2e7d373d6021eeed3bfc68803816bd4f6ee30daa/exec/bigmachine.go#L243-L244) more fault-tolerant.
> Accept `func () io.Reader` argument for RPC

- ec2system/ec2machine_test.go
- local.go
- regress/tests/teststream.go
Use loopback address for local communication to avoid exposing ports externally. This has the side effect of not triggering OS X dialogs prompting users to deny/allow access to incoming traffic, in tests and `Local` system usage.
> Use loopback address for local communication

- ec2system/ec2machine_test.go
This fixes test failures that come up often in our (upcoming) GitHub Actions CI.
> Allow broken pipe errors on bad certificates

- ec2system/ec2machine.go
- internal/authority/authority.go
Use in-memory PEM instead of re-reading PEM from file. This eliminates a race when multiple `bigmachine` programs are reading/writing to the cached authority, e.g.:
1. `A` sees no file at `/tmp/bigmachine.pem`.
2. `B` sees no file at `/tmp/bigmachine.pem`.
3. `A` generates a new authority and writes it to `/tmp/bigmachine.pem`.
4. `B` generates a new authority and writes it to `/tmp/bigmachine.pem`, overwriting `A`'s authority.
5. `A` re-reads the authority contents, which is then passed to machines.
6. `A` client certificate cannot be used to connect to the machines.
> Use in-memory PEM instead of re-reading from file

- ec2system/config.go
- ec2system/ec2machine.go
CoreOS has reached [the end of its life ](https://coreos.com/os/eol/). Flatcar is a [drop-in replacement](https://www.flatcar-linux.org/).
Flatcar documentation says that `cloud-init`, which Bigmachine uses, [is deprecated](https://docs.flatcar-linux.org/os/provisioning/#migrating-from-cloud-configs). However, the developers say that ["`cloud-config` will continue to work ... for the foreseeable future."](https://groups.google.com/g/flatcar-linux-user/c/DTjvoOwZlIk).
> Migrate from CoreOS to Flatcar

- .github/workflows/ci.yml
This also upgrades us to golangci-lint v1.29.
> Upgrade to golangci-lint-action@v2

- .github/workflows/ci.yml
- ec2system/ec2machine.go
Tolerate more `describe-images` errors, retrying when we attempt to start more machines. `describe-images` can fail for reasons like `RequestLimitExceeded`, which are okay to retry (even after the SDK has already retried). Instead of memoizing these failures, forget them, and allow future attempts to start machines to try the call again.
> Tolerate describe-images errors

- machine.go
- machine_test.go
Fail fast when service cannot be gob-encoded. In general, we should fail fast if service registration fails fatally. The current behavior is that we will retry for several minutes.
> Fail fast when service cannot be gob-encoded

- machine_test.go
- rpc/server.go
Fail fast when `(service).Init` panics. We make the assumption that a panic in `Init` is unrecoverable, so we fail fast, so it's faster (fails faster) and easier (less log noise) to recognize.
Note that we're taking a conservative approach. If `Init` merely returns a non-fatal error, we will still retry.
> Fail fast on (service).Init panic
